language: go
sudo: false

go:
  - 1.11.x

before_install:
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -v -service=travis-ci

after_success:
  - CGO_ENABLED=0 go build -o app